clear

%main directory
cd('/ubc/ece/home/ll/grads/kenl/MSC_Project')

%this needs to be modified to where we have saved
%simulated data
%read in csv files for each modulation
X_bpsk = csvread('Data/BPSK/X_bpsk_15.csv');
X_oqpsk = csvread('Data/OQPSK/X_oqpsk_15.csv');
X_bfskA = csvread('Data/BFSKA/X_bfskA_15.csv');
X_bfskB = csvread('Data/BFSKB/X_bfskB_15.csv');
X_bfskR2 = csvread('Data/BFSKR2/X_bfskR2_15.csv');
X_ook = csvread('Data/OOK/X_ook_15.csv');

%m1
%this needs to be changed to where we stored the 
%.fig files Kuba sent us
openfig('Visualizations/Preprocess/Paper/Boxplot_m1.fig');
%recall column 2 of simulated data stores parameter 'm1'
%this section of code preps the input data to create
%boxplot in matlab
m1_val = [X_ook(:,2); X_bpsk(:,2); X_oqpsk(:,2); ...
	X_bfskA(:,2); X_bfskB(:,2); X_bfskR2(:,2)];
m1_names = [repmat({'s1'}, length(X_ook), 1); ...
	repmat({'s2'}, length(X_bpsk), 1); ...
	repmat({'s3'}, length(X_oqpsk), 1); ...
	repmat({'s4'}, length(X_bfskA), 1); ...
	repmat({'s5'}, length(X_bfskB), 1); ...
	repmat({'s6'}, length(X_bfskR2), 1)];
%holds the current kuba figure
hold on;
%overlay current kuba figure with our simulated data
boxplot(m1_val, m1_names, 'colors', 'ggg', 'symbol', 'gx', ...
'boxstyle', 'filled', 'medianstyle', 'target');
h = gcf;
%this needs to be changed to desired output destination
saveas(h, 'Visualizations/Preprocess/Paper/Boxplot_m1.eps', 'eps')
saveas(h, 'Visualizations/Preprocess/Paper/Boxplot_m1.pdf', 'pdf')

%m2
openfig('Visualizations/Preprocess/Paper/Boxplot_m2.fig');
m2_val = [X_ook(:,3); X_bpsk(:,3); X_oqpsk(:,3); ...
	X_bfskA(:,3); X_bfskB(:,3); X_bfskR2(:,3)];
m2_names = [repmat({'s1'}, length(X_ook), 1); ...
	repmat({'s2'}, length(X_bpsk), 1); ...
	repmat({'s3'}, length(X_oqpsk), 1); ...
	repmat({'s4'}, length(X_bfskA), 1); ...
	repmat({'s5'}, length(X_bfskB), 1); ...
	repmat({'s6'}, length(X_bfskR2), 1)];
hold on;
boxplot(m2_val, m2_names, 'colors', 'ggg', 'symbol', 'gx', ...
'boxstyle', 'filled', 'medianstyle', 'target');
h = gcf;
saveas(h, 'Visualizations/Preprocess/Paper/Boxplot_m2.eps', 'eps')
saveas(h, 'Visualizations/Preprocess/Paper/Boxplot_m2.pdf', 'pdf')

%m3
openfig('Visualizations/Preprocess/Paper/Boxplot_m3.fig');
m3_val = [X_ook(:,4); X_bpsk(:,4); X_oqpsk(:,4); ...
	X_bfskA(:,4); X_bfskB(:,4); X_bfskR2(:,4)];
m3_names = [repmat({'s1'}, length(X_ook), 1); ...
	repmat({'s2'}, length(X_bpsk), 1); ...
	repmat({'s3'}, length(X_oqpsk), 1); ...
	repmat({'s4'}, length(X_bfskA), 1); ...
	repmat({'s5'}, length(X_bfskB), 1); ...
	repmat({'s6'}, length(X_bfskR2), 1)];
hold on;
boxplot(m3_val, m3_names, 'colors', 'ggg', 'symbol', 'gx', ...
'boxstyle', 'filled', 'medianstyle', 'target');
h = gcf;
saveas(h, 'Visualizations/Preprocess/Paper/Boxplot_m3.eps', 'eps')
saveas(h, 'Visualizations/Preprocess/Paper/Boxplot_m3.pdf', 'pdf')

%m4
openfig('Visualizations/Preprocess/Paper/Boxplot_m4.fig');
m4_val = [X_ook(:,5); X_bpsk(:,5); X_oqpsk(:,5); ...
	X_bfskA(:,5); X_bfskB(:,5); X_bfskR2(:,5)];
m4_names = [repmat({'s1'}, length(X_ook), 1); ...
	repmat({'s2'}, length(X_bpsk), 1); ...
	repmat({'s3'}, length(X_oqpsk), 1); ...
	repmat({'s4'}, length(X_bfskA), 1); ...
	repmat({'s5'}, length(X_bfskB), 1); ...
	repmat({'s6'}, length(X_bfskR2), 1)];
hold on;
boxplot(m4_val, m4_names, 'colors', 'ggg', 'symbol', 'gx', ...
'boxstyle', 'filled', 'medianstyle', 'target');
h = gcf;
saveas(h, 'Visualizations/Preprocess/Paper/Boxplot_m4.eps', 'eps')
saveas(h, 'Visualizations/Preprocess/Paper/Boxplot_m4.pdf', 'pdf')

%m5
openfig('Visualizations/Preprocess/Paper/Boxplot_m5.fig');
m5_val = [X_ook(:,6); X_bpsk(:,6); X_oqpsk(:,6); ...
	X_bfskA(:,6); X_bfskB(:,6); X_bfskR2(:,6)];
m5_names = [repmat({'s1'}, length(X_ook), 1); ...
	repmat({'s2'}, length(X_bpsk), 1); ...
	repmat({'s3'}, length(X_oqpsk), 1); ...
	repmat({'s4'}, length(X_bfskA), 1); ...
	repmat({'s5'}, length(X_bfskB), 1); ...
	repmat({'s6'}, length(X_bfskR2), 1)];
hold on;
boxplot(m5_val, m5_names, 'colors', 'ggg', 'symbol', 'gx', ...
'boxstyle', 'filled', 'medianstyle', 'target');
h = gcf;
saveas(h, 'Visualizations/Preprocess/Paper/Boxplot_m5.eps', 'eps')
saveas(h, 'Visualizations/Preprocess/Paper/Boxplot_m5.pdf', 'pdf')




